# Generated by Django 5.0.1 on 2025-11-14 07:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                ("client_email", models.EmailField(max_length=254)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Portfolios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("BOND", "Bond"),
                            ("CASH", "Cash"),
                            ("ETF", "ETF"),
                            ("MUTUAL_FUND", "Mutual Fund"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("valuation_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Holdings",
                "ordering": ["-valuation_date", "asset_name"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "valuation_date"],
                        name="portfolio_h_portfol_833eb3_idx",
                    ),
                    models.Index(
                        fields=["valuation_date"], name="portfolio_h_valuati_23f255_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ValuationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_aum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_snapshots",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Valuation Snapshots",
                "ordering": ["-snapshot_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "snapshot_date"],
                        name="portfolio_v_portfol_9c1c55_idx",
                    ),
                    models.Index(
                        fields=["status"], name="portfolio_v_status_c9a541_idx"
                    ),
                ],
                "unique_together": {("portfolio", "snapshot_date")},
            },
        ),
    ]
